### ISSUE TITLE
Package won't importing

### ISSUE THREAD

**Issue by ZhymabekRoman** [ZhymabekRoman/Platonus_API_Wrapper#4]
```
Traceback (most recent call last):
  File "/data/sdext2/data/com.termux/files/home/git/test.py", line 1, in <module>
    from platonus_api_wrapper import PlatonusAPI
  File "<frozen zipimport>", line 259, in load_module
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/platonus_api_wrapper-0.3a0-py3.9.egg/platonus_api_wrapper/__init__.py", line 7, in <module>
ModuleNotFoundError: No module named 'platonus_api_wrapper.base'
```
Не пойму в чем проблема (

**Comment by ZhymabekRoman** [comment]
Попробовал установить на удаленный сервер - такая же проблема

**Comment by ZhymabekRoman** [comment]
Временный костыль для решения проблемы: 
echo "export PYTHONPATH=<ПУТЬ К КЛОНИРОВАННОЙ РЕПОЗИТОРИИ>" >> ~/.bashrc

**Comment by ZhymabekRoman** [comment]
Попробовал задать вопрос в StackOverflow - никто так и не помог = (
https://stackoverflow.com/questions/66684680/problem-during-package-import-does-not-want-to-import-correctly
